name: Production

on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build
        run: |
          echo "${{ secrets.ENV }}" > .env
          npm run build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 cp ./build/index.html s3://about-hoseung/index.html --cache-control no-cache,must-revalidate,s-maxage=31536000
          aws s3 sync ./build s3://about-hoseung --delete --exclude "*.html" --cache-control max-age=31536000
          aws cloudfront create-invalidation --distribution-id E31H7NOZM0QJVH --paths "/*"
